### ISSUE TITLE
Feature Request: Pull From Banker

### ISSUE THREAD

**Issue by GrubbyZebra** [war3i4i/Marketplace#6]
The trader UI has an option to send coins from sales directly to the banker, would be nice if there was the option to do the inverse of that and pull coins directly from the banker when buying.

This would free up considerable weight capacity for actual goods.

**Comment by war3i4i** [comment]
Will try

**Comment by war3i4i** [comment]
![image](https://github.com/war3i4i/Marketplace/assets/60820906/46147d78-01c6-4892-a412-bbdec7cb565f)

in progress

**Comment by war3i4i** [comment]
48dadc8 done, needs testing tho

**Comment by GrubbyZebra** [comment]
how to turn this on? Running Marketplace v9.0.14
