### ISSUE TITLE
Feature: Additional NPC Animations

### ISSUE THREAD

**Issue by GrubbyZebra** [war3i4i/Marketplace#7]
Would it be possible to add some additional animations for the NPCs? Specifcally, the pickaxe and hoe/cultivator animations? Or does the mod already allow that since the animations are part of the base game?

**Comment by war3i4i** [comment]
NPC's can use any player animations if its Player or Player_Female, or any humanoid model with @humanoid in NPC model override. You just need to find animation trigger name in unity project and write it

**Comment by GrubbyZebra** [comment]
excellent. I thought that might be the case as I was typing the request.
WIll dig through the libraries to find the trigger.

Loving this mod!
